#!/usr/bin/env python3
"""tools/mkarms.py — materialize the six instruction-surface arms.

    tools/mkarms.py --repo fixtures/<repo> --out fixtures/<repo>.arms \
        --seed <trial>            -> a0/ a1/ a2/ a3/ a4/ a5/

One script, one source of truth, so no arm drifts from another (design
§4). Each output directory is an **overlay**: a `_arm.json` manifest
naming paths to delete from the sandbox, plus the files to write. The
runner applies it after materializing the repo, so the same checkout
serves every arm.

| arm | surface | isolates |
| --- | ------- | -------- |
| a0 | nothing | floor: what does *any* instruction cost or buy |
| a1 | the repo's own maintainer-written file, verbatim | practical baseline |
| a2 | router + every context concatenated, order seeded | delivery mechanism, content held constant |
| a3 | router + `.subagents/`, as shipped | the pattern |
| a4 | a3, plus context-scoped spawn | E3 |
| a5 | ~40-line file + language tooling | minimal-instruction alternative |

**A2 is the scientific control.** It exists so the comparison is not
"directed contexts vs fewer words". It is generated by concatenating
exactly the files A3 exposes, and `assert_a2_matches_a3` verifies that
byte-for-byte rather than trusting the generator — design §4 says assert
it in P0, do not assume it.

**A1 is recovered, never authored.** If the repo ships no instruction
file, A1 is `n/a` and A0 carries the floor. Synthesizing one would let
the reader wonder whether the baseline was built to lose.
"""
from __future__ import annotations

import argparse
import json
import random
import shutil
import sys
from pathlib import Path

ARMS = ("a0", "a1", "a2", "a3", "a4", "a5")

# Delimiters are content-free and stable so A2 can be split back into the
# exact blocks it was built from. Changing them breaks the A2 == A3
# assertion, which is the intended failure mode.
BEGIN = "<!-- mkarms:begin {path} -->"
END = "<!-- mkarms:end {path} -->"

ROUTER_CANDIDATES = ("AGENTS.md", "CLAUDE.md")
CONTEXT_DIR = ".subagents"

A5_TEMPLATE = """# Agent instructions

Work in this repository using the language tooling available to you.

- Locate code with the editor's own symbol search before reading whole files.
- Run the project's tests before claiming a change works.
- Keep changes scoped to the task; do not reformat untouched code.
- Follow the conventions of the file you are editing.
- If a change spans subsystems, say so rather than guessing at one.
"""


def _read(p: Path) -> str:
    return p.read_text(errors="replace")


def contexts(repo: Path) -> list[Path]:
    """Every context module A3 exposes, in stable sorted order."""
    d = repo / CONTEXT_DIR
    if not d.is_dir():
        return []
    return sorted(p for p in d.rglob("*.md") if p.is_file())


def router(repo: Path) -> Path | None:
    for name in ROUTER_CANDIDATES:
        p = repo / name
        if p.is_file():
            return p
    return None


def _blocks(repo: Path) -> list[tuple[str, str]]:
    """(relative path, content) for the router and every context — the
    exact set A3 exposes and A2 must contain."""
    out = []
    r = router(repo)
    if r:
        out.append((r.relative_to(repo).as_posix(), _read(r)))
    for c in contexts(repo):
        out.append((c.relative_to(repo).as_posix(), _read(c)))
    return out


def build_a2(repo: Path, seed: int) -> str:
    """Router + all contexts concatenated.

    `seed=0` preserves source order — the closest thing to a monolith a
    human would have written. Non-zero seeds randomize section order to
    neutralize position effects.

    Both exist because the randomization is not free: a randomly-ordered
    monolith may be worse than any real one, which would let the treatment
    win by the control being degraded rather than by bounding working. The
    registration requires A2 at both orderings, and treats a large gap
    between them as a finding about ordering that outranks the A2-vs-A3
    comparison (docs/EVAL.md §The control may be handicapped).

    The router block stays first either way — a router buried mid-document
    is a different treatment, not a shuffled one."""
    blocks = _blocks(repo)
    if not blocks:
        return ""
    head, rest = blocks[0], blocks[1:]
    if seed:
        random.Random(seed).shuffle(rest)
    parts = []
    for path, content in [head] + rest:
        parts.append(BEGIN.format(path=path))
        parts.append(content)
        parts.append(END.format(path=path))
    return "\n".join(parts) + "\n"


def split_a2(text: str) -> list[tuple[str, str]]:
    """Inverse of build_a2: recover (path, content) from the monolith."""
    out, i = [], 0
    while True:
        b = text.find("<!-- mkarms:begin ", i)
        if b < 0:
            return out
        path = text[b + len("<!-- mkarms:begin "):text.find(" -->", b)]
        cstart = text.find(" -->", b) + len(" -->\n")
        e = text.find(END.format(path=path), cstart)
        if e < 0:
            return out
        out.append((path, text[cstart:e]))
        i = e + 1


def assert_a2_matches_a3(out_dir: Path) -> list[str]:
    """A2 must be exactly the concatenation of what A3 exposes — same
    paths, same bytes. Verified from the written artifacts, not from the
    in-memory values that produced them, so a bug in the writer is caught
    too."""
    problems = []
    a2 = out_dir / "a2" / "AGENTS.md"
    a3 = out_dir / "a3"
    if not a2.is_file():
        return ["a2/AGENTS.md missing"]

    recovered = dict(split_a2(_read(a2)))
    exposed = {}
    for p in sorted(a3.rglob("*")):
        if p.is_file() and p.name != "_arm.json":
            exposed[p.relative_to(a3).as_posix()] = _read(p)

    missing = sorted(set(exposed) - set(recovered))
    extra = sorted(set(recovered) - set(exposed))
    if missing:
        problems.append(f"A2 is missing content A3 exposes: {missing}")
    if extra:
        problems.append(f"A2 contains content A3 does not expose: {extra}")
    for path in sorted(set(exposed) & set(recovered)):
        # Trailing-newline handling is the only normalization allowed;
        # anything else would let real content drift hide behind it.
        if exposed[path].rstrip("\n") != recovered[path].rstrip("\n"):
            problems.append(f"A2 and A3 differ in {path}")
    return problems


def _write_arm(out_dir: Path, arm: str, files: dict[str, str],
               remove: list[str], note: str = "") -> None:
    d = out_dir / arm
    if d.exists():
        shutil.rmtree(d)
    d.mkdir(parents=True)
    for rel, content in files.items():
        p = d / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content)
    (d / "_arm.json").write_text(json.dumps(
        {"arm": arm, "remove": remove, "files": sorted(files),
         "note": note}, indent=2) + "\n")


def mkarms(repo: Path, out_dir: Path, seed: int) -> dict:
    out_dir.mkdir(parents=True, exist_ok=True)
    r = router(repo)
    ctxs = contexts(repo)
    # Every arm starts by clearing whatever instruction surface the repo
    # ships, so no arm silently inherits another's.
    strip = [n for n in ROUTER_CANDIDATES if (repo / n).is_file()]
    if (repo / CONTEXT_DIR).is_dir():
        strip.append(CONTEXT_DIR)

    _write_arm(out_dir, "a0", {}, strip,
               "no instruction file; carries the floor")

    if r:
        _write_arm(out_dir, "a1", {r.name: _read(r)}, strip,
                   "recovered verbatim from the repository, not authored")
    else:
        _write_arm(out_dir, "a1", {}, strip,
                   "n/a: repository ships no maintainer instruction file; "
                   "A0 carries the floor (design §4)")

    _write_arm(out_dir, "a2", {"AGENTS.md": build_a2(repo, seed)}, strip,
               f"router + {len(ctxs)} contexts concatenated, seed={seed}")

    a3_files = {}
    if r:
        a3_files[r.name] = _read(r)
    for c in ctxs:
        a3_files[c.relative_to(repo).as_posix()] = _read(c)
    _write_arm(out_dir, "a3", a3_files, strip, "the pattern as shipped")
    _write_arm(out_dir, "a4", dict(a3_files), strip,
               "same surface as a3; dispatch is context-scoped (E3)")

    _write_arm(out_dir, "a5", {"AGENTS.md": A5_TEMPLATE}, strip,
               "minimal instruction file; language tooling supplies the rest")

    problems = assert_a2_matches_a3(out_dir)
    return {"repo": str(repo), "out": str(out_dir), "seed": seed,
            "router": r.name if r else None, "n_contexts": len(ctxs),
            "arms": list(ARMS), "a2_matches_a3": not problems,
            "problems": problems}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()
    rep = mkarms(Path(args.repo), Path(args.out), args.seed)
    print(json.dumps(rep, indent=2))
    if rep["problems"]:
        print("\nA2 != A3 — the scientific control is invalid; "
              "do not run arms from this directory.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
