#!/usr/bin/env python3
"""Turn a verified task set into scenarios the runner can execute.

    python3 -m adherence.mkscenarios --tasks scenarios-pr/cli-cli \\
        --mirror fixtures/cli-cli.git --fixture cli-cli

Reads `ground-truth.jsonl` (produced and *verified* by `adherence.mkpr`)
and writes one scenario directory per task, plus a suite file listing
them. Each scenario is ordinary to the runner — same `scenario.yaml`,
same grader contract — so nothing downstream needs to know these came
from PRs.

The grader is shared: every PR task uses `adherence.prgrade`, so there is
one implementation of the registered protocol rather than one per task.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

GRADE_SHIM = '''"""Generated by adherence.mkscenarios — do not edit.

Every PR-derived task shares one grader so the registered protocol has a
single implementation. See adherence.prgrade.
"""
from adherence.prgrade import grade  # noqa: F401
'''


def yaml_escape(text: str) -> str:
    """scenario.yaml is read by runner.load_yamlish, which takes a quoted
    one-line string with \\n escapes."""
    return (text.replace("\\", "\\\\").replace('"', '\\"')
                .replace("\n", "\\n").replace("\r", ""))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tasks", required=True, help="dir with ground-truth.jsonl")
    ap.add_argument("--mirror", required=True)
    ap.add_argument("--fixture", required=True, help="fixture label on results")
    ap.add_argument("--out", default="scenarios")
    ap.add_argument("--suite", default="suite-pr.yaml")
    ap.add_argument("--timeout", type=int, default=1800)
    ap.add_argument("--prefix", default="")
    args = ap.parse_args()

    tasks_dir = Path(args.tasks)
    gt = tasks_dir / "ground-truth.jsonl"
    if not gt.is_file():
        sys.exit(f"no ground-truth.jsonl in {tasks_dir} — run `make mkpr` first")

    tasks = [json.loads(x) for x in gt.read_text().splitlines() if x.strip()]
    unverified = [t for t in tasks if t.get("verified") == "unverified"]
    if unverified:
        print(f"WARNING: {len(unverified)} task(s) were never verified "
              f"fail-before/pass-after. They can pass without the agent doing "
              f"anything. Re-run mkpr without --no-verify.", file=sys.stderr)

    prefix = args.prefix or args.fixture.replace("/", "-")
    out_root = Path(args.out)
    ids = []
    for t in sorted(tasks, key=lambda x: x["pr"]):
        sid = f"{prefix}-{t['pr']}"
        d = out_root / sid
        d.mkdir(parents=True, exist_ok=True)
        (d / "grade.py").write_text(GRADE_SHIM)
        (d / "scenario.yaml").write_text(
            "# Generated by adherence.mkscenarios from a merged PR.\n"
            "# The prompt has had file paths stripped: locating the work is\n"
            "# the thing under measurement. The agent never sees the tests.\n"
            f"category: pr\n"
            f"fixture: {args.fixture}\n"
            f"repo: {args.mirror}\n"
            f"base_commit: {t['base_commit']}\n"
            f"timeout: {args.timeout}\n"
            f"expects_edit: 1\n"
            f'prompt: "{yaml_escape(t["prompt"])}"\n')
        # The grader needs the test files and command, and the agent must
        # not: it lands as a dotfile the runner commits into the baseline
        # so it never appears as an agent edit, and it names no source path
        # the prompt withheld.
        (d / "task.json").write_text(json.dumps({
            "pr": t["pr"], "merge_commit": t["merge_commit"],
            "test_files": t["test_files"], "test_cmd": t["test_cmd"],
            "code_files": t["code_files"],
        }, indent=2) + "\n")
        ids.append(sid)

    Path(args.suite).write_text(
        "# Generated by adherence.mkscenarios. Regenerate; do not hand-edit.\n"
        "scenarios:\n" + "".join(f"  - {i}\n" for i in ids))

    print(f"wrote {len(ids)} scenarios to {out_root}/ and {args.suite}")
    print(f"probe them with:  make probe SUITE={args.suite}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
